---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postiz-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: postiz-platform
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 20.x.x
      helm:
        releaseName: postiz-redis
        valueFiles:
          - $values/03-redis/values.yaml
    - repoURL: "REPLACE_WITH_REPO_URL"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: postiz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
