---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postiz-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: postiz-platform
  source:
    repoURL: "REPLACE_WITH_REPO_URL"
    targetRevision: main
    path: 05-postiz
    directory:
      include: 'ingress.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: postiz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
