# syntax=docker/dockerfile:1.7
# Multi-stage build for the cloudless app, targeting linux/arm64 (Pi 5).
# Produces a self-contained image using Next.js' standalone output mode.
#
# Build:
#   docker buildx build --platform linux/arm64 -t cloudless-pi-app:dev .
#
# Run:
#   docker run --rm -p 3000:3000 --env-file .env.local cloudless-pi-app:dev

ARG NODE_VERSION=22-alpine
ARG PNPM_VERSION=10.33.2

# ──────────────────────────────────────────────────────────────────────────────
# 1) deps — install all production+dev deps (cached on lockfile only)
# ──────────────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS deps
ARG PNPM_VERSION
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY patches ./patches
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --prefer-offline

# ──────────────────────────────────────────────────────────────────────────────
# 2) builder — compile Next.js with standalone output
# ──────────────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS builder
ARG PNPM_VERSION
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate
WORKDIR /app

# Public env vars baked into the client bundle at build time.
# Pass via --build-arg (NEXT_PUBLIC_*) — they're not secrets.
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_COGNITO_USER_POOL_ID
ARG NEXT_PUBLIC_COGNITO_CLIENT_ID
ARG NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL} \
    NEXT_PUBLIC_COGNITO_USER_POOL_ID=${NEXT_PUBLIC_COGNITO_USER_POOL_ID} \
    NEXT_PUBLIC_COGNITO_CLIENT_ID=${NEXT_PUBLIC_COGNITO_CLIENT_ID} \
    NEXT_PUBLIC_HUBSPOT_PORTAL_ID=${NEXT_PUBLIC_HUBSPOT_PORTAL_ID} \
    NEXT_OUTPUT_STANDALONE=1 \
    NEXT_TELEMETRY_DISABLED=1

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN pnpm build

# ──────────────────────────────────────────────────────────────────────────────
# 3) runner — minimal runtime image
# ──────────────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

# Non-root user (uid 1000 — matches the Deployment's runAsUser)
RUN addgroup -S -g 1000 cloudless && adduser -S -u 1000 -G cloudless cloudless

# Copy the standalone bundle, which contains only the production node_modules
# Next.js needs at runtime, plus the server entry point.
COPY --from=builder --chown=cloudless:cloudless /app/.next/standalone ./
COPY --from=builder --chown=cloudless:cloudless /app/.next/static ./.next/static
COPY --from=builder --chown=cloudless:cloudless /app/public ./public

USER cloudless
EXPOSE 3000

# server.js is generated by `next build` when output: 'standalone'
CMD ["node", "server.js"]
