# syntax=docker/dockerfile:1.7
# Multi-stage build for the cloudless app, targeting linux/arm64 (Pi 5).
# Produces a self-contained image using Next.js' standalone output mode.
#
# Build:
#   docker buildx build --platform linux/arm64 -t cloudless-pi-app:dev .
#
# Run:
#   docker run --rm -p 3000:3000 --env-file .env.local cloudless-pi-app:dev

ARG NODE_VERSION=22-alpine
ARG PNPM_VERSION=10.33.2

# ──────────────────────────────────────────────────────────────────────────────
# 1) deps — install all production+dev deps (cached on lockfile only)
# ──────────────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS deps
ARG PNPM_VERSION
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc ./
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile --prefer-offline

# ──────────────────────────────────────────────────────────────────────────────
# 2) builder — compile Next.js with standalone output
# ──────────────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS builder
ARG PNPM_VERSION
RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate
WORKDIR /app

# Public env vars baked into the client bundle at build time.
# Pass via --build-arg (NEXT_PUBLIC_*) — they're not secrets.
ARG NEXT_PUBLIC_SITE_URL=https://cloudless.gr
ARG NEXT_PUBLIC_STAGE=production
ARG NEXT_PUBLIC_COGNITO_USER_POOL_ID
ARG NEXT_PUBLIC_COGNITO_CLIENT_ID
ARG NEXT_PUBLIC_COGNITO_DOMAIN=https://cloudless-auth.auth.us-east-1.amazoncognito.com
ARG NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_META_PIXEL_ID
ARG NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION
# APP_VERSION is the deployed commit SHA — exposed via /api/health so the
# HA speed-sync orchestrator can compare cloud vs Pi served versions.
ARG APP_VERSION=dev
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL} \
    NEXT_PUBLIC_STAGE=${NEXT_PUBLIC_STAGE} \
    NEXT_PUBLIC_COGNITO_USER_POOL_ID=${NEXT_PUBLIC_COGNITO_USER_POOL_ID} \
    NEXT_PUBLIC_COGNITO_CLIENT_ID=${NEXT_PUBLIC_COGNITO_CLIENT_ID} \
    NEXT_PUBLIC_COGNITO_DOMAIN=${NEXT_PUBLIC_COGNITO_DOMAIN} \
    NEXT_PUBLIC_HUBSPOT_PORTAL_ID=${NEXT_PUBLIC_HUBSPOT_PORTAL_ID} \
    NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN} \
    NEXT_PUBLIC_META_PIXEL_ID=${NEXT_PUBLIC_META_PIXEL_ID} \
    NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=${NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION} \
    APP_VERSION=${APP_VERSION} \
    NEXT_OUTPUT_STANDALONE=1 \
    NEXT_TELEMETRY_DISABLED=1 \
    NODE_OPTIONS="--max-old-space-size=768"

COPY --from=deps /app/node_modules ./node_modules
# Recursive copy of the build context. Safe because .dockerignore excludes
# secrets, .git, .env*, tests, docs, and other non-build artifacts.
COPY . .
RUN pnpm build

# ──────────────────────────────────────────────────────────────────────────────
# 3) runner — minimal runtime image
# ──────────────────────────────────────────────────────────────────────────────
FROM node:${NODE_VERSION} AS runner
WORKDIR /app

# Re-declare APP_VERSION here so the runtime stage receives the build-arg.
# Multi-stage builds don't inherit ARGs across FROM boundaries — without
# this re-declaration + ENV pass-through, /api/health.version would
# silently fall back to the static "0.1.0" default in src/app/api/health
# even though the workflow passed --build-arg APP_VERSION=<sha>.
ARG APP_VERSION=dev
ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0 \
    APP_VERSION=${APP_VERSION}

# node:22-alpine ships with a non-root `node` user at uid/gid 1000 — reuse it
# (matches the k3s Deployment's runAsUser: 1000). --chmod=0555 drops write bits
# on the copied resources so the runtime user can't tamper with the bundle.
COPY --from=builder --chown=node:node --chmod=0555 /app/.next/standalone ./
COPY --from=builder --chown=node:node --chmod=0555 /app/.next/static ./.next/static
COPY --from=builder --chown=node:node --chmod=0555 /app/public ./public

# The Next.js image optimizer (/_next/image) writes optimized variants to
# .next/cache/images at request time. The bundle above is copied --chmod=0555
# (read-only), so without a writable cache dir owned by the runtime user the
# first /_next/image request fails with EACCES on mkdir (Sentry CLOUDLESS-GR-5).
RUN mkdir -p .next/cache/images && chown -R node:node .next/cache

USER node
EXPOSE 3000

# server.js is generated by `next build` when output: 'standalone'
CMD ["node", "server.js"]
