-- Supabase starter SQL schema for a Nuxt app with user management, roles, and storage
-- This script creates tables, roles, and policies for a typical app

-- 1. Profiles table (linked to Supabase Auth users)
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  website text,
  constraint username_length check (char_length(username) >= 3)
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using (true);

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile."
  on public.profiles for update
  using (auth.uid() = id);

-- 2. Example: Projects table (customize as needed)
create table if not exists public.projects (
  id uuid default gen_random_uuid() primary key,
  owner uuid references public.profiles(id) on delete cascade,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc', now()) not null
);

alter table public.projects enable row level security;

create policy "Project is viewable by everyone."
  on public.projects for select
  using (true);

create policy "Project owner can update/delete."
  on public.projects for update using (auth.uid() = owner)
  on public.projects for delete using (auth.uid() = owner);

-- 3. Storage: Avatars bucket and policies
insert into storage.buckets (id, name) values ('avatars', 'avatars') on conflict do nothing;

create policy "Avatar images are publicly accessible."
  on storage.objects for select
  using (bucket_id = 'avatars');

create policy "Anyone can upload an avatar."
  on storage.objects for insert
  with check (bucket_id = 'avatars');

-- 4. Realtime publication
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.profiles, public.projects;

-- 5. Example: User roles and permissions (customize as needed)
create type public.app_role as enum ('admin', 'moderator', 'user');

create table if not exists public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  role public.app_role not null,
  unique (user_id, role)
);

-- 6. Grant usage to Supabase system roles (optional, for advanced use)
grant usage on schema public to supabase_auth_admin;

-- Add more tables and policies as needed for your app.

SELECT * FROM profiles;
