/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AdminNotifications": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AnalyticsCache": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "CloudlessSite": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "SessionTokenStore": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "StripeTransactions": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserProfile": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}

import "sst"
export {}