/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnalyticsRollupHandler": import("@cloudflare/workers-types").Service
    "AnalyticsWorker": import("@cloudflare/workers-types").Service
    "CalendarDigestHandler": import("@cloudflare/workers-types").Service
    "ReportCleanupHandler": import("@cloudflare/workers-types").Service
    "VoiceBriefHandler": import("@cloudflare/workers-types").Service
  }
}

import "sst"
export {}