ingress_rule:
  hostname: n8n.cloudless.gr
  service: http://192.168.1.128:30900
  originRequest:
    connectTimeout: 15s
    tcpKeepAlive: 30s
    noTLSVerify: false
    httpHostHeader: n8n.cloudless.gr
