import { createVuetify } from 'vuetify'
// Import only needed components for better tree-shaking
import {
  VApp,
  VMain,
  VContainer,
  VRow,
  VCol,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VBtn,
  VTextField,
  VTextarea,
  VSelect,
  VCheckbox,
  VRadio,
  VRadioGroup,
  VSwitch,
  VSlider,
  VAlert,
  VSnackbar,
  VDialog,
  VMenu,
  VTooltip,
  VChip,
  VAvatar,
  VIcon,
  VList,
  VListItem,
  VListItemTitle,
  VListItemSubtitle,
  VDivider,
  VTabs,
  VTab,
  VTabsWindow,
  VTabsWindowItem,
  VForm,
  VImg,
  VProgressCircular,
  VProgressLinear,
  VNavigationDrawer,
  VAppBar,
  VToolbar,
  VToolbarTitle,
  VSpacer,
  VDataTable,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelTitle,
  VExpansionPanelText
} from 'vuetify/components'
import * as directives from 'vuetify/directives'
import { defineNuxtPlugin } from '#app'
import { aliases, mdi } from 'vuetify/iconsets/mdi'

export default defineNuxtPlugin((nuxtApp) => {
  const vuetify = createVuetify({
    components: {
      VApp,
      VMain,
      VContainer,
      VRow,
      VCol,
      VCard,
      VCardTitle,
      VCardText,
      VCardActions,
      VBtn,
      VTextField,
      VTextarea,
      VSelect,
      VCheckbox,
      VRadio,
      VRadioGroup,
      VSwitch,
      VSlider,
      VAlert,
      VSnackbar,
      VDialog,
      VMenu,
      VTooltip,
      VChip,
      VAvatar,
      VIcon,
      VList,
      VListItem,
      VListItemTitle,
      VListItemSubtitle,
      VDivider,
      VTabs,
      VTab,
      VTabsWindow,
      VTabsWindowItem,
      VForm,
      VImg,
      VProgressCircular,
      VProgressLinear,
      VNavigationDrawer,
      VAppBar,
      VToolbar,
      VToolbarTitle,
      VSpacer,
      VDataTable,
      VExpansionPanels,
      VExpansionPanel,
      VExpansionPanelTitle,
      VExpansionPanelText
    },
    directives,
    icons: {
      defaultSet: 'mdi',
      aliases,
      sets: {
        mdi,
      },
    },
    theme: {
      defaultTheme: 'light',
      themes: {
        light: {
          colors: {
            primary: '#1976D2',
            secondary: '#424242',
            accent: '#82B1FF',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            background: '#FAFAFA',
            surface: '#FFFFFF',
          },
        },
        dark: {
          colors: {
            primary: '#2196F3',
            secondary: '#424242',
            accent: '#FF4081',
            error: '#FF5252',
            info: '#2196F3',
            success: '#4CAF50',
            warning: '#FFC107',
            background: '#121212',
            surface: '#1E1E1E',
          },
        },
      },
    },
    defaults: {
      VBtn: {
        style: 'text-transform: none;',
      },
      VCard: {
        elevation: 2,
      },
    },
  })
  
  nuxtApp.vueApp.use(vuetify)
})
