apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-engine
  namespace: oncall
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-celery
  namespace: oncall
spec:
  replicas: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-redis
  namespace: oncall
spec:
  replicas: 0
---
# StatefulSet for mariadb — replicas: 0 preserves PVCs
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oncall-mariadb
  namespace: oncall
spec:
  replicas: 0
