import type { MetadataRoute } from "next";
import { readFileSync } from "fs";
import { join } from "path";
import { posts } from "@/lib/blog";
import { defaultProducts } from "@/lib/store-products";
import { getCaseStudies, staticCaseStudies } from "@/lib/notion-case-studies";
import { isConfiguredAsync } from "@/lib/integrations";

// ISR-cache sitemap.xml so the Notion → Sitemap Sync workflow
// (notion-docs-sitemap.yml) still takes effect without a redeploy, but
// crawler requests don't pay the Notion fetch latency on every hit.
//
// Previously declared `dynamic = "force-dynamic"` alongside
// `revalidate = 3600`, which is contradictory — `force-dynamic` opts
// out of all caching and makes `revalidate` a no-op. Result: the
// `/sitemap.xml` route did the full Notion + TSV walk on every crawler
// hit and clocked ~1.75 s vs ~600 ms for `/api/health`. With
// `force-dynamic` removed, Next.js emits `s-maxage=3600`, the CDN
// caches the response, and only one request per hour pays the build
// cost.
export const revalidate = 3600;

// Render sitemap.xml on each request rather than baking it at build time so
// Notion ? Sitemap Sync (notion-docs-sitemap.yml) doesn't need a redeploy
// to take effect. Revalidate at most hourly to keep the CDN warm for crawlers.
export const dynamic = "force-dynamic";
export const revalidate = 3600;

// ---------------------------------------------------------------------------
// Static page last-modified dates
//
// Update a date here whenever meaningful content changes on that page.
// Using new Date() would reset every date on every build — even for pages
// that haven't changed — which harms crawl-priority signals.
// ---------------------------------------------------------------------------
const LAST_MODIFIED: Record<string, string> = {
  "/": "2026-06-18",
  "/services": "2026-06-18",
  "/store": "2026-04-19",
  "/blog": "2026-06-17",
  "/contact": "2026-04-19",
  // Store product catalogue — bump when the catalogue is updated
  "/store/products": "2026-04-19",
};

/** Build language alternates for a locale-agnostic path (e.g. "/blog/slug") */
function localeAlternates(path: string) {
  const base = "https://cloudless.gr";
  return {
    languages: {
      en: (base + "/en" + path) as string,
      el: (base + "/el" + path) as string,
      fr: (base + "/fr" + path) as string,
      de: (base + "/de" + path) as string,
      "x-default": (base + "/en" + path) as string,
    },
  };
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const baseUrl = "https://cloudless.gr";

  const staticPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(LAST_MODIFIED["/"]),
      changeFrequency: "weekly",
      priority: 1,
      alternates: localeAlternates(""),
    },
    {
      url: `${baseUrl}/services`,
      lastModified: new Date(LAST_MODIFIED["/services"]),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/store`,
      lastModified: new Date(LAST_MODIFIED["/store"]),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: new Date(LAST_MODIFIED["/blog"]),
      changeFrequency: "weekly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: new Date(LAST_MODIFIED["/contact"]),
      changeFrequency: "monthly",
      priority: 0.7,
    },
  ];

  // Blog posts already carry their own publish date — use it directly
  const blogPages: MetadataRoute.Sitemap = posts.map((post) => ({
    url: `${baseUrl}/blog/${post.slug}`,
    lastModified: new Date(post.date),
    changeFrequency: "monthly" as const,
    priority: 0.6,
    alternates: localeAlternates(`/blog/${post.slug}`),
  }));

  // Products don't carry an individual last-modified date; share the
  // catalogue date so it only resets when the catalogue is actually updated
  const catalogueDate = new Date(LAST_MODIFIED["/store/products"]);
  const productPages: MetadataRoute.Sitemap = defaultProducts.map((product) => ({
    url: `${baseUrl}/store/${product.id}`,
    lastModified: catalogueDate,
    changeFrequency: "monthly" as const,
    priority: 0.5,
  }));

  // Case studies (Notion-backed with static fallback)
  let caseStudyList = staticCaseStudies;
  try {
    const configured = await isConfiguredAsync("NOTION_API_KEY", "NOTION_CASE_STUDIES_DB_ID");
    if (configured) caseStudyList = await getCaseStudies();
  } catch {
    // fall back to static list
  }
  const caseStudyPages: MetadataRoute.Sitemap = caseStudyList.map((cs) => ({
    url: `${baseUrl}/case-studies/${cs.slug}`,
    lastModified: new Date(cs.date),
    changeFrequency: "monthly" as const,
    priority: 0.7,
    alternates: localeAlternates(`/case-studies/${cs.slug}`),
  }));

  // Notion-synced pages (docs + blog from Notion)
  // Generated by .github/workflows/notion-docs-sitemap.yml
  let notionPages: MetadataRoute.Sitemap = [];
  try {
    const tsvPath = join(process.cwd(), "src/data/notion-sitemap-entries.tsv");
    const raw = readFileSync(tsvPath, "utf-8");
    notionPages = raw
      .split("\n")
      .filter((line) => line && !line.startsWith("#"))
      .map((line) => {
        const [path, lastmod] = line.split("\t");
        return {
          url: `${baseUrl}${path}`,
          lastModified: lastmod ? new Date(lastmod) : new Date(),
          changeFrequency: "weekly" as const,
          priority: path.startsWith("/docs/") ? 0.6 : 0.65,
        };
      });
  } catch {
    // TSV file may not exist yet — no Notion pages in sitemap
  }

  return [...staticPages, ...blogPages, ...productPages, ...caseStudyPages, ...notionPages];
}
