apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: cloudless-cloudwatch-exporter
    app.kubernetes.io/part-of: cloudless
  name: cloudless-cloudwatch-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudless-cloudwatch-exporter
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '9106'
        prometheus.io/scrape: 'true'
      labels:
        app.kubernetes.io/name: cloudless-cloudwatch-exporter
        app.kubernetes.io/part-of: cloudless
    spec:
      containers:
        - args:
            - /config/config.yml
            - '9106'
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: cloudless-cloudwatch-exporter-aws
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: cloudless-cloudwatch-exporter-aws
          image: prom/cloudwatch-exporter:v0.15.5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          name: cloudwatch-exporter
          ports:
            - containerPort: 9106
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /metrics
              port: http
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
      volumes:
        - configMap:
            defaultMode: 420
            name: cloudless-cloudwatch-exporter-config
          name: config
