apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cloudless-cloudwatch-exporter
    app.kubernetes.io/part-of: cloudless
  name: cloudless-cloudwatch-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    port: 9106
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: cloudless-cloudwatch-exporter
  type: ClusterIP
