#!/usr/bin/env python3
"""Write /etc/rancher/k3s/config.yaml from environment variables —
credentials are never stored in a file that might be shared or
committed.

Usage (run on the Pi as root):
  sudo ETCD_S3_ACCESS_KEY=… ETCD_S3_SECRET_KEY=… \\
      python3 scripts/configure-k3s.py
  sudo systemctl restart k3s

Optional env (defaults match the live cluster): ETCD_S3_BUCKET,
ETCD_S3_REGION, ETCD_S3_FOLDER, TLS_SAN_VIP, TLS_SAN_LAN,
TLS_SAN_TS, TLS_SAN_MAGICDNS, DATA_DIR"""

import os
import sys
import time
from pathlib import Path

for var in ("ETCD_S3_ACCESS_KEY", "ETCD_S3_SECRET_KEY"):
    if not os.environ.get(var):
        sys.exit(f"{var} must be set")

BUCKET = os.environ.get("ETCD_S3_BUCKET", "cloudless-etcd-snapshots")
REGION = os.environ.get("ETCD_S3_REGION", "us-east-1")
FOLDER = os.environ.get("ETCD_S3_FOLDER", "etcd")
VIP = os.environ.get("TLS_SAN_VIP", "192.168.1.200")
LAN = os.environ.get("TLS_SAN_LAN", "192.168.1.128")
TS = os.environ.get("TLS_SAN_TS", "100.74.191.58")
MAGIC = os.environ.get("TLS_SAN_MAGICDNS", "github-omv.tail4ecae1.ts.net")

if os.geteuid() != 0:
    sys.exit("run as root (sudo)")

CONFIG = Path("/etc/rancher/k3s/config.yaml")
CONFIG.parent.mkdir(parents=True, exist_ok=True)

if CONFIG.is_file():
    bak = CONFIG.with_suffix(f".yaml.bak.{time.strftime('%Y%m%dT%H%M%S')}")
    bak.write_bytes(CONFIG.read_bytes())
    print("[configure-k3s] backed up existing config")

ts_now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
CONFIG.write_text(f"""# Generated by scripts/configure-k3s.py on {ts_now}
# Edit via: sudo ETCD_S3_ACCESS_KEY=… ETCD_S3_SECRET_KEY=… ./scripts/configure-k3s.py
# See k3s/config.example.yaml for field reference.

cluster-init: true
secrets-encryption: true
flannel-backend: wireguard-native

tls-san:
  - "{VIP}"
  - "{LAN}"
  - "{TS}"
  - "{MAGIC}"

kube-apiserver-arg:
  - "service-node-port-range=1000-32767"

etcd-snapshot-schedule-cron: "0 */6 * * *"
etcd-snapshot-retention: 3
etcd-s3: true
etcd-s3-bucket: {BUCKET}
etcd-s3-region: {REGION}
etcd-s3-folder: {FOLDER}
etcd-s3-access-key: {os.environ["ETCD_S3_ACCESS_KEY"]}
etcd-s3-secret-key: {os.environ["ETCD_S3_SECRET_KEY"]}
etcd-s3-insecure: false

etcd-arg:
  - heartbeat-interval=300
  - election-timeout=3000
  - quota-backend-bytes=2147483648
  - auto-compaction-retention=1h
  - auto-compaction-mode=periodic

# Kubelet resource reservations (bumped 2026-05-29 memory=300Mi →
# 800Mi after a k3s flap storm traced to apiserver context-deadline
# timeouts during etcd compaction).
kubelet-arg:
  - max-pods=110
  - eviction-hard=memory.available<200Mi
  - image-gc-high-threshold=80
  - image-gc-low-threshold=70
  - system-reserved=cpu=300m,memory=400Mi
  - kube-reserved=cpu=400m,memory=800Mi
""")
CONFIG.chmod(0o600)
print(f"[configure-k3s] wrote {CONFIG} (mode 600)")
print("[configure-k3s] restart k3s to apply: sudo systemctl restart k3s")
