#!/usr/bin/env bash
# Write /etc/rancher/k3s/config.yaml from environment variables.
#
# Use this instead of editing config.yaml directly so credentials are never
# stored in a file that might be shared or accidentally committed.
#
# Source-of-truth lives in this repo (was previously only on the Pi). After
# editing, sync to the Pi and re-apply:
#   scp scripts/configure-k3s.sh tbaltzakis@192.168.1.128:~/OMV/scripts/
#   ssh tbaltzakis@192.168.1.128 \
#     'sudo ETCD_S3_ACCESS_KEY=… ETCD_S3_SECRET_KEY=… ~/OMV/scripts/configure-k3s.sh && \
#      sudo systemctl restart k3s'
#
# Usage:
#   sudo \
#     ETCD_S3_ACCESS_KEY=AKIAxxxxxxxx \
#     ETCD_S3_SECRET_KEY=xxxxxxxx \
#     ./scripts/configure-k3s.sh
#
# Optional env (all have defaults matching the live cluster):
#   ETCD_S3_BUCKET    cloudless-etcd-snapshots
#   ETCD_S3_REGION    us-east-1
#   ETCD_S3_FOLDER    etcd
#   TLS_SAN_VIP       192.168.1.200
#   TLS_SAN_LAN       192.168.1.128
#   DATA_DIR          /srv/dev-disk-by-uuid-a9a5a108-8095-4b7b-8011-716889995cd7/k3s
#
# After writing the config, restart k3s to apply:
#   sudo systemctl restart k3s

set -euo pipefail

: "${ETCD_S3_ACCESS_KEY:?ETCD_S3_ACCESS_KEY must be set}"
: "${ETCD_S3_SECRET_KEY:?ETCD_S3_SECRET_KEY must be set}"

ETCD_S3_BUCKET="${ETCD_S3_BUCKET:-cloudless-etcd-snapshots}"
ETCD_S3_REGION="${ETCD_S3_REGION:-us-east-1}"
ETCD_S3_FOLDER="${ETCD_S3_FOLDER:-etcd}"
TLS_SAN_VIP="${TLS_SAN_VIP:-192.168.1.200}"
TLS_SAN_LAN="${TLS_SAN_LAN:-192.168.1.128}"

if [[ ${EUID} -ne 0 ]]; then
  echo "run as root (sudo)" >&2; exit 1
fi

CONFIG=/etc/rancher/k3s/config.yaml
install -d -m 0755 /etc/rancher/k3s

# Back up existing config if present
if [[ -f "${CONFIG}" ]]; then
  cp "${CONFIG}" "${CONFIG}.bak.$(date +%Y%m%dT%H%M%S)"
  echo "[configure-k3s] backed up existing config"
fi

cat > "${CONFIG}" <<EOF
# Generated by scripts/configure-k3s.sh on $(date -u +%FT%TZ)
# Edit via: sudo ETCD_S3_ACCESS_KEY=… ETCD_S3_SECRET_KEY=… ./scripts/configure-k3s.sh
# See k3s/config.example.yaml for field reference.

cluster-init: true
secrets-encryption: true
flannel-backend: wireguard-native

tls-san:
  - "${TLS_SAN_VIP}"
  - "${TLS_SAN_LAN}"

kube-apiserver-arg:
  - "service-node-port-range=1000-32767"

# CLAUDE.md "k3s Tuning" requires hourly snapshots; the previous
# "0 */6 * * *" lagged the omv-backup-verify watchdog (SLO 2h). The
# k3s-snapshot-mirror.timer (every 30 min) under
# infrastructure/etcd-backup/ keeps the NAS backup mount in sync.
etcd-snapshot-schedule-cron: "0 */1 * * *"
etcd-snapshot-retention: 24
etcd-s3: true
etcd-s3-bucket: ${ETCD_S3_BUCKET}
etcd-s3-region: ${ETCD_S3_REGION}
etcd-s3-folder: ${ETCD_S3_FOLDER}
etcd-s3-access-key: ${ETCD_S3_ACCESS_KEY}
etcd-s3-secret-key: ${ETCD_S3_SECRET_KEY}
etcd-s3-insecure: false

etcd-arg:
  - heartbeat-interval=300
  - election-timeout=3000
  - quota-backend-bytes=2147483648
  - auto-compaction-retention=1h
  - auto-compaction-mode=periodic

# Kubelet resource reservations.
#
# Bumped 2026-05-29 from memory=300Mi → 800Mi after a k3s flap storm
# (21 restarts in 3h) traced to apiserver context-deadline timeouts during
# etcd compaction. The host has 7.9 GiB; 300 MiB reserved was too tight,
# leaving kubelet + container-runtime in the same cgroup pool as user pods
# during compaction RAM spikes.
#
# Reserves: kubelet + k3s server itself.
# system-reserved covers OS daemons (sshd, systemd-journald, OMV plugins).
# eviction-hard kicks in once user-pod memory pushes available below 200Mi.
kubelet-arg:
  - max-pods=110
  - eviction-hard=memory.available<200Mi
  - image-gc-high-threshold=80
  - image-gc-low-threshold=70
  - system-reserved=cpu=300m,memory=400Mi
  - kube-reserved=cpu=400m,memory=800Mi
EOF

chmod 600 "${CONFIG}"
echo "[configure-k3s] wrote ${CONFIG} (mode 600)"
echo "[configure-k3s] restart k3s to apply: sudo systemctl restart k3s"
