#!/usr/bin/env python3
"""Setup Cloudflare Email Sending DNS records (SPF, DKIM, DMARC)
programmatically for noreply@cloudless.gr deliverability.

Usage: CLOUDFLARE_API_TOKEN=... \
    python3 scripts/setup-email-deliverability.py
  DOMAIN env (default cloudless.gr)"""

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request

DOMAIN = os.environ.get("DOMAIN", "cloudless.gr")
API = "https://api.cloudflare.com/client/v4"

token = os.environ.get("CLOUDFLARE_API_TOKEN", "")
if not token:
    r = subprocess.run(["gh", "secret", "view",
                        "CLOUDFLARE_API_TOKEN"],
                       capture_output=True, text=True)
    if r.returncode == 0:
        token = r.stdout.strip()
if not token:
    sys.exit("CLOUDFLARE_API_TOKEN is required")


def cf(method: str, path: str, body: dict | None = None) -> dict:
    req = urllib.request.Request(
        f"{API}{path}",
        data=json.dumps(body).encode() if body is not None else None,
        method=method,
        headers={"Authorization": f"Bearer {token}",
                 "Content-Type": "application/json"})
    try:
        return json.loads(urllib.request.urlopen(req,
                                                 timeout=15).read())
    except Exception:
        return {"result": []}


print(f"🔧 Setting up Cloudflare Email deliverability for "
      f"{DOMAIN}...\n")

zones = cf("GET", f"/zones?name={DOMAIN}").get("result") or []
if not zones:
    sys.exit(f"ERROR: Zone not found for {DOMAIN}")
zone_id = zones[0]["id"]
print(f"✓ Zone ID: {zone_id}")


def create_dns_record(rtype: str, name: str, content: str) -> None:
    exists = cf("GET", f"/zones/{zone_id}/dns_records?type={rtype}"
                       f"&name={name}").get("result")
    if not exists:
        r = cf("POST", f"/zones/{zone_id}/dns_records",
               {"type": rtype, "name": name, "content": content,
                "ttl": 3600, "proxied": False})
        res = r.get("result") or {}
        print(f"{res.get('name', name)} ({res.get('type', rtype)}): "
              f"{res.get('content', content)}")
        print("✓ Added")
    else:
        print(f"✓ {rtype} record for {name} already exists")


print("\n[1/5] Configuring SPF record...")
create_dns_record("TXT", DOMAIN,
                  "v=spf1 include:cloudflare.net ~all")

print("\n[2/5] Getting/creating DKIM records...")
# DKIM records are auto-generated by Cloudflare Email — noted only.

print("\n[3/5] Adding DMARC record...")
create_dns_record("TXT", f"_dmarc.{DOMAIN}",
                  f"v=DMARC1; p=none; rua=mailto:postmaster@{DOMAIN}")

print("\n[4/5] Checking MX records...")
mx = cf("GET", f"/zones/{zone_id}/dns_records?type=MX"
               f"&name={DOMAIN}").get("result") or []
if not mx:
    print("No MX records configured (this is fine for Email "
          "Sending only)")
else:
    print("MX records found:")
    for r in mx:
        print(f"  - {r['name']} -> {r['content']} "
              f"(priority {r.get('priority')})")

print("\n[5/5] Verifying email routing status...")
status = cf("GET", f"/zones/{zone_id}/email/routing")
if status.get("result"):
    res = status["result"]
    print(f"Email routing status: {res.get('status', 'unknown')}")
else:
    print("Email routing may not be enabled — see Cloudflare → "
          "Email → Routing")

print(f"""
==========================================
✅ Email deliverability setup complete!
==========================================
Destination verification goes to the address configured in
Cloudflare Email Routing (see configure-email-routing.py).""")
