#!/bin/bash
# Setup Cloudflare Email Sending DNS records (SPF, DKIM) programmatically
# Uses Cloudflare API to ensure email deliverability for noreply@cloudless.gr

set -euo pipefail

DOMAIN="${DOMAIN:-cloudless.gr}"
CF_API_TOKEN="${CLOUDFLARE_API_TOKEN:-}"

# Get token from gh secret if not in environment
if [ -z "$CF_API_TOKEN" ]; then
    CF_TOKEN=$(gh secret view CLOUDFLARE_API_TOKEN 2>/dev/null || echo "")
    export CLOUDFLARE_API_TOKEN="$CF_TOKEN"
fi

: "${CLOUDFLARE_API_TOKEN:?CLOUDFLARE_API_TOKEN is required}"

echo "🔧 Setting up Cloudflare Email deliverability for ${DOMAIN}..."
echo ""

# Get Zone ID
ZONE_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" \
    | jq -r '.result[0].id')

if [ -z "$ZONE_ID" ] || [ "$ZONE_ID" = "null" ]; then
    echo "ERROR: Zone not found for ${DOMAIN}"
    exit 1
fi

echo "✓ Zone ID: ${ZONE_ID}"

# Function to create DNS record if it doesn't exist
create_dns_record() {
    local type="$1"
    local name="$2"
    local content="$3"
    
    # Check if exists
    local existing=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?type=${type}&name=${name}" \
        -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
        -H "Content-Type: application/json" \
        | jq -r '.result | length')
    
    if [ "$existing" -eq 0 ]; then
        curl -s -X POST "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "{
                \"type\": \"${type}\",
                \"name\": \"${name}\",
                \"content\": \"${content}\",
                \"ttl\": 3600,
                \"proxied\": false
            }" | jq -r '.result.name + " (" + .result.type + "): " + .result.content'
        echo "✓ Added"
    else
        echo "✓ ${type} record for ${name} already exists"
    fi
}

# Step 1: SPF Record for email deliverability
echo ""
echo "[1/5] Configuring SPF record..."
create_dns_record "TXT" "${DOMAIN}" "v=spf1 include:cloudflare.net ~all"

# Step 2: DKIM records (these come from Cloudflare Email configuration)
echo ""
echo "[2/5] Getting/creating DKIM records..."
# DKIM records are typically auto-generated by Cloudflare Email
# Format: cloudflare-domain-verification=..., k=rsa, p=...
# For now, we'll note that DKIM may be auto-managed

# Step 3: DMARC record (optional but recommended)
echo ""
echo "[3/5] Adding DMARC record..."
create_dns_record "_dmarc.${DOMAIN}" "_dmarc.${DOMAIN}" "v=DMARC1; p=none; rua=mailto:postmaster@${DOMAIN}"

# Step 4: Check MX records (only if you want to receive email)
echo ""
echo "[4/5] Checking MX records..."
MX_RECORDS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?type=MX&name=${DOMAIN}" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" | jq -r '.result | length')

if [ "$MX_RECORDS" -eq 0 ]; then
    echo "No MX records configured (this is fine for Email Sending only)"
else
    echo "MX records found:"
    curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/dns_records?type=MX&name=${DOMAIN}" \
        -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
        -H "Content-Type: application/json" | jq -r '.result[] | "  - " + .name + " -> " + .content + " (priority " + (.priority|tostring) + ")"'
fi

# Step 5: Verify Email configuration in Cloudflare
echo ""
echo "[5/5] Checking Email configuration status..."
EMAIL_STATUS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}/email/routing/setup" \
    -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
    -H "Content-Type: application/json" | jq -r '.result.status // "not_configured"')

echo "Email Routing Status: ${EMAIL_STATUS}"

echo ""
echo "=========================================="
echo "✅ Email Configuration Complete!"
echo "=========================================="
echo ""
echo "SPF record: v=spf1 include:cloudflare.net ~all"
echo "DMARC record: v=DMARC1; p=none; rua=mailto:postmaster@${DOMAIN}"
echo ""
echo "To verify Email Sending works:"
echo "1. Deploy the worker: pnpm cf:deploy:free"
echo "2. Test the contact endpoint: curl -X POST https://cloudless.gr/api/contact -d '...'"
echo ""
echo "Current worker code uses: env.EMAIL.send() with from: noreply@${DOMAIN}"