#!/usr/bin/env python3
"""Tunnel Configuration Sync — applies routes.yaml to cloudflared
config on omv (192.168.1.128).

Generates ingress rules for every active route, writes
/etc/cloudflared/config.yml (backup first), reloads cloudflared."""

import subprocess
import sys
import tempfile
from pathlib import Path

OMV_HOST = "192.168.1.128"
OMV_USER = "tbaltzakis"
CLOUDFLARED_CONFIG = "/etc/cloudflared/config.yml"
TUNNEL_ID = "e977a490-58c5-4fdb-9155-86832e3e636a"

ROOT = Path(__file__).resolve().parent.parent
ROUTES = ROOT / "infrastructure/cloudflare-tunnels/routes.yaml"

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None


def load_routes() -> list[dict]:
    if yaml:
        data = yaml.safe_load(ROUTES.read_text())
        return [r for r in (data.get("routes") or [])
                if r.get("status") == "active"]
    # Minimal fallback parser — routes.yaml is a flat list of mappings
    routes, cur = [], {}
    for ln in ROUTES.read_text().splitlines():
        ln = ln.strip()
        if ln.startswith("- hostname:") or ln.startswith("hostname:"):
            if cur:
                routes.append(cur)
            cur = {"hostname": ln.split(":", 1)[1].strip()}
        elif ":" in ln and cur is not None:
            k, v = ln.split(":", 1)
            cur[k.strip().lstrip("- ")] = v.strip()
    if cur:
        routes.append(cur)
    return [r for r in routes if r.get("status") == "active"]


print("Generating ingress rules from routes.yaml...")
rules = []
for r in load_routes():
    host = r.get("hostname", "")
    port = r.get("port", "")
    if not host or not port:
        continue
    rules.append(
        f"- hostname: {host}\n"
        f"  service: http://localhost:{port}\n"
        "  originRequest:\n"
        "    connectTimeout: 15s\n"
        "    tcpKeepAlive: 30s\n"
        f"    httpHostHeader: {host}")
ingress = "\n".join(rules)

print(f"Applying to omv ({OMV_HOST})...")
subprocess.run(["ssh", f"{OMV_USER}@{OMV_HOST}",
                "sudo mkdir -p /etc/cloudflared"], check=True)

config = f"""# Generated by tunnel-sync script
# Do not edit manually - update infrastructure/cloudflare-tunnels/routes.yaml instead

tunnel: {TUNNEL_ID}
credentials-file: /etc/cloudflared/credentials.json

ingress:
{ingress}
  - service: http_status:404
"""

with tempfile.NamedTemporaryFile("w", suffix=".yml",
                                 delete=False) as f:
    f.write(config)
    tmp = f.name

subprocess.run(["scp", tmp, f"{OMV_USER}@{OMV_HOST}:/tmp/config.yml.new"],
               check=True)
Path(tmp).unlink()

subprocess.run(
    ["ssh", f"{OMV_USER}@{OMV_HOST}",
     f"sudo cp {CLOUDFLARED_CONFIG} {CLOUDFLARED_CONFIG}.bak "
     "2>/dev/null || true; "
     f"sudo mv /tmp/config.yml.new {CLOUDFLARED_CONFIG}; "
     "sudo systemctl reload cloudflared"], check=True)

print("Tunnel configuration applied successfully!")
print("Verify with: curl -I https://manage.cloudless.gr")
