#!/bin/bash
# Tunnel Configuration Sync Script
# Applies routes.yaml to cloudflared config on omv (192.168.1.128)

set -e

OMV_HOST="192.168.1.128"
OMV_USER="tbaltzakis"
CLOUDFLARED_CONFIG="/etc/cloudflared/config.yml"

# Generate ingress rules from routes.yaml
generate_ingress() {
  yq '.routes[] | select(.status == "active") | 
    "- hostname: \(.hostname)\n  service: http://localhost:\(.port)\n  originRequest:\n    connectTimeout: 15s\n    tcpKeepAlive: 30s\n    httpHostHeader: \(.hostname)"' \
    infrastructure/cloudflare-tunnels/routes.yaml
}

echo "Generating ingress rules from routes.yaml..."
INGRESS_RULES=$(generate_ingress)

echo "Applying to omv ($OMV_HOST)..."
ssh "$OMV_USER@$OMV_HOST" "sudo mkdir -p /etc/cloudflared"

# Create temp file with new config
TEMP_FILE=$(mktemp)
cat > "$TEMP_FILE" << EOF
# Generated by tunnel-sync script
# Do not edit manually - update infrastructure/cloudflare-tunnels/routes.yaml instead

tunnel: e977a490-58c5-4fdb-9155-86832e3e636a
credentials-file: /etc/cloudflared/credentials.json

ingress:
$INGRESS_RULES
  - service: http_status:404
EOF

# Copy to omv
scp "$TEMP_FILE" "$OMV_USER@$OMV_HOST:/tmp/config.yml.new"
rm "$TEMP_FILE"

# Backup and apply
ssh "$OMV_USER@$OMV_HOST" "
  sudo cp $CLOUDFLARED_CONFIG $CLOUDFLARED_CONFIG.bak 2>/dev/null || true
  sudo mv /tmp/config.yml.new $CLOUDFLARED_CONFIG
  sudo systemctl reload cloudflared
"

echo "Tunnel configuration applied successfully!"
echo "Verify with: curl -I https://manage.cloudless.gr"